# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/protos/v1/appuser/appuser.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api/protos/v1/appuser/appuser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#api/protos/v1/appuser/appuser.proto\x12\nv1.appuser\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n\x07\x41ppuser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x30\n\ronline_status\x18\x03 \x01(\x0e\x32\x19.v1.appuser.AppUserStatus\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"-\n\rCreateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"\x10\n\x0e\x43reateResponse*\xa1\x01\n\rAppUserStatus\x12\x1f\n\x1b\x41PP_USER_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x41PP_USER_STATUS_INACTIVE\x10\x01\x12\x1a\n\x16\x41PP_USER_STATUS_ONLINE\x10\x02\x12\x1b\n\x17\x41PP_USER_STATUS_OFFLINE\x10\x03\x12\x18\n\x14\x41PP_USER_STATUS_AWAY\x10\x04\x32Q\n\x0e\x41ppuserService\x12?\n\x06\x43reate\x12\x19.v1.appuser.CreateRequest\x1a\x1a.v1.appuser.CreateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.protos.v1.appuser.appuser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPUSERSTATUS']._serialized_start=338
  _globals['_APPUSERSTATUS']._serialized_end=499
  _globals['_APPUSER']._serialized_start=85
  _globals['_APPUSER']._serialized_end=270
  _globals['_CREATEREQUEST']._serialized_start=272
  _globals['_CREATEREQUEST']._serialized_end=317
  _globals['_CREATERESPONSE']._serialized_start=319
  _globals['_CREATERESPONSE']._serialized_end=335
  _globals['_APPUSERSERVICE']._serialized_start=501
  _globals['_APPUSERSERVICE']._serialized_end=582
# @@protoc_insertion_point(module_scope)
