[project]
name = "mist-api"
version = "0.1.0"
description = "API Services for the Mist project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.5",
    "django-cors-headers>=4.6.0",
    "djangorestframework>=3.15.2",
    "djangorestframework-simplejwt>=5.4.0",
    "grpcio>=1.70.0",
    "grpcio-tools>=1.70.0",
    "psycopg2-binary>=2.9.10",
]

[dependency-groups]
dev = ["ruff>=0.9.4"]


[tool.ruff]
# Set the maximum line length to 79.
line-length = 120
