[tool.poetry]
name = "mist-api"
version = "0.1.0"
description = "API Services for the Mist project"
authors = ["Omar Cruz Pantoja"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.4"
djangorestframework = "^3.15"
djangorestframework-simplejwt = "^5.3.1"
psycopg2-binary = "^2.9.10"
django-cors-headers = "^4.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
