when:
  - event: manual

steps:
  - name: Fetch and Initialize Credentials
    when:
      - evaluate: 'DEPLOY_DEV == "true"'
    image: registry.mist-project.app/mist-shared/alpine-ci:latest
    environment:
      OP_SERVICE_ACCOUNT_TOKEN:
        from_secret: OP_TOKEN
      OP_VAULT:
        from_secret: OP_VAULT
      TENANT_ACCOUNT_ID: "4wccsugzybkttewdtm2zujm5gu"
      SERVICE_ACCOUNT_ID: "dtq7g2fd6xenfh44mwp56hohtq"

    commands:
      - chmod +x helpers/fetch_creds_op.sh
      - ./helpers/fetch_creds_op.sh

  - name: Build Image and Push to Registry
    when:
      - evaluate: 'MANUAL_DEPLOY == "true"'
    image: woodpeckerci/plugin-kaniko
    privileged: true

    settings:
      repo: mist-auth
      dockerfile: Dockerfile
      tags:
        - latest # TODO: Add version tag or commit sha for incremental versions
      registry: registry.mist-project.app
      log-level: info

  - name: Pull latest image in tenant
    when:
      - evaluate: 'MANUAL_DEPLOY == "true"'
    image: registry.mist-project.app/mist-shared/alpine-ci:latest
    environment:
      ANSIBLE_HOST_KEY_CHECKING: False
    commands:
      - source .tmpenvs
      - |
        ansible-playbook -i ansible/inventory/hosts.ini \
          ansible/playbooks/deploy.yml \
          --extra-vars "ansible_ssh_private_key_file=key.pem" \
          --extra-vars "ansible_user=$TENANT_USERNAME" \
          --extra-vars "APP_PORT=$APP_PORT" \
          --extra-vars "DATABASE_USER=$DATABASE_USER" \
          --extra-vars "DATABASE_PASSWORD=$DATABASE_PASSWORD" \
          --extra-vars "DATABASE_HOST=$DATABASE_HOST" \
          --extra-vars "DATABASE_PORT=$DATABASE_PORT" \
          --extra-vars "DATABASE_NAME=$DATABASE_NAME" \
          --extra-vars "APP_JWT_SECRET_KEY=$APP_JWT_SECRET_KEY" \
          --extra-vars "APP_JWT_AUDIENCES=$APP_JWT_AUDIENCES" \
          --extra-vars "APP_JWT_ISSUER=$APP_JWT_ISSUER" \
          --extra-vars "APP_SECRET_KEY=$APP_SECRET_KEY" \
          --extra-vars "MIST_BACKEND_APP_URL=$MIST_BACKEND_APP_URL" \
